title: andreyka26 tech
google_analytics: G-71R0HBMGS3
description: >- # this means to ignore newlines until "baseurl:"
  I am Software Engineer at Microsoft. This is my tech blog where I would like to share my findings, guides and docs. Feel free to contact me.

url: "https://andreyka26.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

widedefault: "/assets/wide-default.png"
squaredefault: "/assets/square-default.png"

# Navigation
urls:
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Categories
    url: /categories
  - text: Privacy Policy
    url: /privacy-policy
  - text: Terms of Use
    url: /terms-of-use

# Edit Author details (For multi authors check _data/authors.yml)
author_logo: profile.png
author: Andrii Bui
author_bio: Hi, my name is Andrii. I'm Software Engineer at Microsoft with 7 years of experience.
author_location: Ukraine
typewrite-text: Master Leetcode & FAANG Interviews | Software Architecture | Authorization & Security | DevOps & Infrastructure
hero_cover_img: sample_cover.png # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: https://microsoft.com
    designation: Software Engineer
    description: I am acting as Software Engineer working on Backend services for M365
    visibility: true
  - company_name: Epam Systems
    company_logo: epam.png
    company_url: https://www.epam.com
    designation: Senior Software Engineer
    description: Developing project with Oil domain(the project is under NDA). The system is a search service that searches through a lot of external and internal systems and services(REST API, SOAP, SQL Server, Cognitive Search). Playing the key software engineer role on the backend side, designing and implementing software architecture, improve performance, provide security compliance. Also developing and maintaining Java Solution which works with active directory and Kafka acting as an ETL job.
    visibility: true
  - company_name: Eleks
    company_logo: eleks.png
    company_url: https://www.eleks.com
    designation: Middle Software Engineer
    description: Developing new features, designing application architecture, and maintaining current behavior on 2C2P (https://www.2c2p.com/). The system is a payment gateway between different payment providers. Playing the role as a key developer on the project delegated to me along with the QA team.
    visibility: true
  - company_name: Magnise
    company_logo: magnise.jfif
    company_url: https://magnise.com
    designation: Junior Software Engineer
    description: Developing the news monitoring system Alphateka (https://alphateka.com). The system monitors social networks, online news, TV, and Radio. It provides quick articles/posts querying with sentiment and clustering analysis. It is able to build analytical charts on the data and notify about different alerts. Playing the role as a backend developer along with 2 frontend developers, 3 backend developers, PM, QA.
    visibility: true

# social links
github_username: andreyka26-git
facebook_username: profile.php?id=100017215509428
linkedin_username: andrii-bui-a55b39166
instagram_username: andreyka26_se
telegram_username: programming_space
youtube_username: "@andreyka26_se"

# Giscus comments
giscus:
  repo: "andreyka26-git/andreyka26-git.github.io"
  repo_id: "R_kgDOIz7kpw"
  category: "Q&A"
  category_id: "DIC_kwDOIz7kp84CuwJu"
  mapping: "url"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "top"
  theme: "gruvbox"
  lang: "en"

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: /:title

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: false

defaults:
  - scope:
      path: "assets/**"
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# Performance optimizations
incremental: true
profile: true
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
  # Exclude all documentation and changelog files from bower_components
  - assets/bower_components/**/*.md
  - assets/bower_components/**/*.txt
  - assets/bower_components/**/README*
  - assets/bower_components/**/CHANGELOG*
  - assets/bower_components/**/changelog*
  - assets/bower_components/**/ChangeLog*
  - assets/bower_components/**/LICENSE*
  - assets/bower_components/**/CONTRIBUTING*
  - assets/bower_components/**/example/
  - assets/bower_components/**/examples/
  - assets/bower_components/**/test/
  - assets/bower_components/**/tests/
  - assets/bower_components/**/docs/
  - assets/bower_components/**/doc/

destination: ./build
